# Secrets should never be manually logged, this example is purely for demonstation purposes.
name: GitHub Actions Environment

on:
    push:
        branches:
            - main
            - dev

jobs:
    deploy-development:
        name: Deploy to Development
        if: github.event.ref == 'refs/heads/dev'
        runs-on: ubuntu-latest
        environment: development
        steps:
            - run: |
                temp=$(echo "${{ secrets.TestSecret }}" | base64)
                echo "🔎 The secret for development is $temp"
    deploy-staging:
        name: Deploy to Staging
        if: github.event.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - run: |
                temp=$(echo "${{ secrets.TestSecret }}" | base64)
                echo "🔎 The secret for development is $temp"
  